# Generated by Django 5.1.6 on 2025-02-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_job_experience_job_job_type_job_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='experience',
            new_name='experience_max',
        ),
        migrations.AddField(
            model_name='job',
            name='experience_min',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
