# Generated by Django 5.1.6 on 2025-02-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_experience_job_experience_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
